CHANGELOG.md
lib/async.dart
lib/src/async_cache.dart
pubspec.yaml
test/async_cache_test.dart

As discussed, and closes https://github.com/dart-lang/async/issues/8.
Will edit CHANGELOG and pubspec and squash before merge.

Add AsyncCache

---

lib/src/stream_subscription_transformer.dart

Removing an unused import and fixing a dynamic inference.

Two small strong-mode/warning fixes

---

CHANGELOG.md
lib/src/async_memoizer.dart
lib/src/cancelable_operation.dart
lib/src/delegate/future.dart
lib/src/lazy_stream.dart
lib/src/utils.dart
pubspec.yaml

Use FutureOr.

---

CHANGELOG.md
lib/src/delegate/stream_subscription.dart
pubspec.yaml

Fix a fuzzy arrow warning

---

pubspec.yaml

Declare support for the latest fake_async

---

CHANGELOG.md
lib/src/result/capture_sink.dart
lib/src/result/capture_transformer.dart
lib/src/stream_splitter.dart
pubspec.yaml
test/result/result_test.dart
test/stream_completer_test.dart
test/stream_group_test.dart

Fix Dart 2 runtime errors

---

lib/src/stream_queue.dart

The original reason to split into an abstract and concrete class was to
allow other implementations that would allow for the transaction
implementation. Since that was implemented without a separate subclass
merge the implementation back to one class to avoid unnecessary
abstraction and make it easier to debug.

Merge _StreamQueue into StreamQueue

---

CHANGELOG.md
lib/src/cancelable_operation.dart
test/cancelable_operation_test.dart

Add isCanceled/Completed to CancelableOperation

---

lib/src/stream_queue.dart

Use a Completer of void

---

.travis.yml

Travis: do browser testing on Chrome

---

lib/src/async_memoizer.dart
lib/src/cancelable_operation.dart

Work around https://github.com/dart-lang/sdk/issues/41106

Add explicit generics to `Future.sync` calls

---

lib/src/stream_sink_transformer/handler_transformer.dart

It is now statically non-null.

Drop defaulting for null StackTrace

---

lib/src/async_memoizer.dart
lib/src/cancelable_operation.dart
pubspec.yaml

These can now be correctly inferred after a fix in the SDK.
https://github.com/dart-lang/sdk/issues/41106

Remove now unnecessary specified generics

---

.travis.yml
CHANGELOG.md
pubspec.yaml

Updates version number and sdk constraint.
Going to attempt to pull this into the SDK after this is merged to master.

prep for null safety release

---

CHANGELOG.md
pubspec.yaml

Bump to stable version of `collection`.

Prepare to publish stable null safety

---

.github/workflows/test-package.yml
CHANGELOG.md
pubspec.yaml
test/result/result_captureAll_test.dart

Fix new pedantic lints, test on oldest supported SDK

---

CHANGELOG.md
lib/src/future_group.dart
lib/src/stream_group.dart
pubspec.yaml
test/stream_group_test.dart

These match the corresponding APIs on FutureGroup.

Add StreamGroup.onIdle and StreamGroup.isIdle

---

CHANGELOG.md
lib/async.dart
lib/src/stream_closer.dart
pubspec.yaml
test/stream_closer_test.dart

This is essentially the Stream equivalent of the Disconnector class in
stream_channel.

Add a StreamCloser transformer

---

CHANGELOG.md
lib/src/stream_group.dart
pubspec.yaml

I forgot to actually push these to the pull request.

Code review changes for #173

---

CHANGELOG.md
lib/src/stream_extensions.dart
pubspec.yaml
test/stream_extensions_test.dart

By analogy to IterableExtensions.firstOrNull in the collection package.

Add StreamExtensions.firstOrNull

---

lib/src/cancelable_operation.dart
lib/src/stream_group.dart
lib/src/stream_queue.dart

Drop use of pkg:collection whereNotNull()
