dart-lang/async

test/async_memoizer_test.dart
test/restartable_timer_test.dart

This fixes `Unused import [UNUSED_IMPORT]` analyzer warnings.

Remove unused imports

---

CHANGELOG.md
lib/src/delegate/future.dart
lib/src/typed/future.dart
pubspec.yaml

The signature is:
`Future<T>.then (<S>((T) → dynamic, {onError: Function}) → Future<S>)`
Use `dynamic` rather than leave off the type to future proof against
`--no-implicit-dynamic`
cleanup: dartfmt

Change signature of methods overriding Future.then

---

CHANGELOG.md
lib/src/stream_queue.dart
pubspec.yaml
test/stream_queue_test.dart

This is important for advanced pull-based stream manipulation. It allows
users to express logic of the form "consume the next events if they
match this predicate".

Add StreamQueue.startTransactions().

---

CHANGELOG.md
lib/src/stream_queue.dart
pubspec.yaml
test/stream_queue_test.dart

This is useful for advanced transaction operations, such as "one of the
following consumers accepts the queue". We want to reliably accept the
same consumer every time, and the best way to do that is to accept the
one that consumed the most events.

Add StreamQueue.eventsDispatched.

---

CHANGELOG.md
lib/src/stream_queue.dart
pubspec.yaml
test/stream_queue_test.dart

This would throw a StateError if StreamQueue.rest had been called on
one of the transaction's child queues, because that queue didn't expect
to be canceled later on.

Bug a bug in StreamQueueTransaction.reject().

---

CHANGELOG.md

This removes entries that aren't relevant to downstream consumers.

Tweak the changelog.

---

test/typed_wrapper/stream_test.dart

We can't test this in 2.0 runtime semantics until test supports a
2.0-compatible platform (dart-lang/test#414).
Closes #35

Skip typed_wrapper/stream_test

---

CHANGELOG.md
lib/src/result/capture_transformer.dart
lib/src/result/release_transformer.dart
lib/src/single_subscription_transformer.dart
lib/src/typed/stream.dart
lib/src/typed_stream_transformer.dart
pubspec.yaml

This makes the initial changes necessary to make this package compatible with the corelib wave 2.2. changes.  See https://github.com/dart-lang/sdk/issues/31847 for more details.

Updates for Dart 2.0 core library changes (wave 2.2)

---

pubspec.yaml

Towards #48
Allows us to run `pub run build_runner test -- -p chrome` to test with
DDC. Exposes issues with the package and with tests so not enabling on
Travis for now.

Add deps for build_runner

---

analysis_options.yaml
lib/src/result/error.dart
lib/src/result/result.dart
lib/src/single_subscription_transformer.dart
pubspec.yaml
test/async_memoizer_test.dart
test/cancelable_operation_test.dart
test/future_group_test.dart
test/lazy_stream_test.dart
test/result/result_future_test.dart
test/result/result_test.dart
test/stream_completer_test.dart
test/stream_group_test.dart
test/stream_queue_test.dart
test/stream_sink_completer_test.dart
test/stream_sink_transformer_test.dart
test/stream_splitter_test.dart
test/stream_zip_test.dart
test/subscription_stream_test.dart
test/typed_wrapper/future_test.dart
test/typed_wrapper/stream_subscription_test.dart
test/utils.dart

This helps rule out some possibilities for the new Dart 2 failure and is
good practice.
Also:
- Update dependencies on build and test packages.
- Ignore todo from the analysis server.
- Move off of deprecated APIs from test.

Enable prefer_typing_uninitialized_variables

---

lib/src/async_cache.dart
test/async_cache_test.dart
test/stream_queue_test.dart

Looks like cache.invalidate does do some asynchronous stuff
(`splitter.close()`, but notably not `_stale.close()` which returns void).
Return the future for that stuff without changing its order of
operations.
Also some place awaiting `expect()` which appeared to be intended to be
awaiting `cancel()`, switching those still passes tests.

Fix places awaiting void, for dart 2.

---

CHANGELOG.md
lib/src/cancelable_operation.dart
pubspec.yaml
test/cancelable_operation_test.dart

Implement CancelableOperation.then

---

CHANGELOG.md
lib/src/restartable_timer.dart
pubspec.yaml

Closes #88
Extra cleanup:
- change a constructor body to an initializer list
- remove an `@override` annotation

Implement RestartableTimer.tick

---

pubspec.yaml
test/stream_group_test.dart

See https://github.com/dart-lang/async/pull/90#discussion_r331247755
Merged streams forward events synchronously so we do know that
guarantees that events keep their order when forwarded. Since it's not
necessary to allow for ordering changes drop the `unorderedEquals`.
Also refactor to async/await from a `completion` matcher.

Check ordering in StreamGroup.merege tests

---

CHANGELOG.md
lib/src/async_memoizer.dart
lib/src/null_stream_sink.dart
lib/src/stream_group.dart

- Remove `new` keyword in code samples.
- Remove `new` keyword in doc reference to named constructors.

Drop optional new from docs

---

analysis_options.yaml
lib/src/cancelable_operation.dart
lib/src/delegate/future.dart
lib/src/future_group.dart
lib/src/result/release_sink.dart
lib/src/result/result.dart
lib/src/stream_sink_completer.dart
test/result/result_captureAll_test.dart
test/result/result_flattenAll_test.dart
test/result/result_test.dart
test/stream_completer_test.dart
test/stream_zip_test.dart
test/utils.dart

- Add an explicit `StackTrace` on arguments to `onError` callback
arguments since they are statically `Function` so no type inference
flows into argument types.
- Add a couple explicit casts.
- Add explicit types on some completers in test code.
- Use `Queue.of` constructor to allow type inference to flow.
- Fix a broken argument type on `DelegatingFuture`.
- Add some missing generic type arguments on fields or arguments.

Fix implicit casts

---

test/stream_splitter_test.dart

Dart 2 provides strong guarantees that the reified type of an object
will be assignable to the static type, this isn't something we need a
runtime test for ourselves.

Remove a stale TODO

---

CHANGELOG.md
README.md
lib/src/delegate/event_sink.dart
lib/src/delegate/sink.dart
lib/src/delegate/stream.dart
lib/src/delegate/stream_consumer.dart
lib/src/delegate/stream_sink.dart
lib/src/delegate/stream_subscription.dart
lib/src/lazy_stream.dart
lib/src/stream_sink_transformer.dart
lib/src/stream_sink_transformer/typed.dart
lib/src/typed_stream_transformer.dart

Towards #98 
Most of these have simpler or safer versions in Dart 2. The "Sink"
classes have a workaround which is ugly, but these also had nearly no
usage.

Deprecate Delegating*.typed utilities

---

test/subscription_stream_test.dart

The breaking change described [here](https://github.com/dart-lang/sdk/issues/40676) changes the return type of StreamSubscription.cancel to `Future<void>` to make it clear that the result value is not intended to be meaningful.  Code that chooses to rely on the return value must now cast through `dynamic`.

Cast use of StreamSubscription.cancel result through dynamic

---

lib/src/cancelable_operation.dart

Closes #102
This field is confusing because it documents whether the backing
completer has had `complete` called which doesn't necessarily correspond
to when the value is available if it was completed with a `Future`.

Expand docs for isCompleted

---

lib/src/cancelable_operation.dart
pubspec.yaml
test/byte_collection_test.dart
test/stream_queue_test.dart

This did result in one api change, which I think is for the better anyways. `CancelableOperation.valueOrCancellation` now has a return type of `T?`, where it would have previously thrown at runtime if you didn't provide a cancellation value.
Also added a workaround for https://github.com/dart-lang/sdk/issues/41156 in one of the tests.

--null-safety fixes, make valueOrCancellation return a T?

---

test/stream_queue_test.dart

https://github.com/dart-lang/sdk/issues/41156 is fixed.

Drop workaround for function type inference

---

.travis.yml
lib/src/lazy_stream.dart
lib/src/result/result.dart
lib/src/single_subscription_transformer.dart
test/result/result_test.dart
test/utils.dart

Same issue as package:pool, error handlers need to return the right type.

fix nnbd tests to run with strong null safety

---

CHANGELOG.md
lib/src/stream_queue.dart
pubspec.yaml

When a `StreamQueue` is created for a broadcast stream, it didn't use to listen to the stream immediately, which means that any events sent before the first call to `next` (or any other queue request) would be silently lost. That makes an initial `peek` operation change the behavior of the queue, which is confusing to users.

Make StreamQueue start listening immediately to broadcast streams.

---

lib/src/cancelable_operation.dart

Replace a dynamic null check with a dynamic type cast, since the target type may be nullable.

Fix error in CancelableOperation.then

---

pubspec.yaml

I still need to fix the clock and async packages for 2.10, and then i will merge them into master and travis will go green here.

restore dev_dependencies and overrides of those

---

lib/src/result/future.dart

Since this version doesn't support Dart 2.0, this import is not
necessary.

Remove unused dart:async import.

---

lib/src/result/error.dart
lib/src/stream_sink_transformer/handler_transformer.dart

- Switch from `StackTrace.fromString` to `AsyncError.defaultStackTrace`.
- Remove a TODO about non-nullable `StackTrace`, by the time we merged
null safety the type was already non-nullable and the TODO was stale.
Style tweak - remove the argument names from a Function type that are
redundant against their type names.

Resolve null safety migration TODOS

---

CHANGELOG.md
lib/src/cancelable_operation.dart
pubspec.yaml

This had been set in the constructor because it needs to reference
`this`. A new capability with `late final` files is to allow an
initializer expression referencing `this`. This approach also avoid
introducing a setter to the public API. The behavior difference is that
the `CancelableOperation` wont be instantiated until it is read, but
this is fine because `CancelableOperation` does not have any side
effects during initialization and it's only field is the
`CancelableCompleter`. Technically it's statically breaking to remove
the setter, but since it could never be called at runtime this is safe
to do.
Also initialize the `_inner` field where it is defined rather than in an
initializer list since there are not multiple constructors that would
assign different values.

Avoid a `late final` field without initializer

---

lib/src/async_cache.dart
test/async_cache_test.dart

When the callback throws an exception, the startStaleTime was not called, so the cache was not refreshed. Because of this, future calls to this cache always returned with the exception.
This pull request solve this issue, by wrapping the `await future` call in a try/finally block.

Invalidate async cache on exception

---

CHANGELOG.md
pubspec.yaml

Drop dependency overrides and update deps to `-nullsafety` versions.

Allow 2.12.0 dev SDK versions

---

CHANGELOG.md
pubspec.yaml
test/utils.dart

The `onError` argument to `runZoned` is deprecated. Switch to the
supported `runZonedGuarded`.
Remove argument types on the function literal since thy can now be
inferred. `runZonedGuarded` has a specific function type argument,
whereas `onError` was typed as `Function` which did not allow inference
on argument types.

Migrate to runZonedGuarded

---

CHANGELOG.md
lib/src/async_cache.dart
lib/src/result/result.dart
lib/src/single_subscription_transformer.dart
lib/src/stream_group.dart
lib/src/stream_zip.dart
lib/src/subscription_stream.dart
pubspec.yaml

This reverts commit 05b9553c81b0168e7665d47730977ca289334a69.
Since this has not been published or rolled through to the SDK or
Flutter we will hold it back to reduce risk.

Revert "Various clean-ups and null-safety improvements. (#140)"

---

lib/async.dart

Fixes #156
The readme, and likely other documentation around the web, has links to
the dartdoc site using the library name "async", which is what the
library would be named in the docs if we omitted the `library` directive
entirely. It is easier to restore the old paths by naming the
library identically than to update all the links.

Use the name that matches no library directive

---

CHANGELOG.md
lib/async.dart
lib/src/chunked_stream_reader.dart
pubspec.yaml
test/chunked_stream_reader.dart

This adds a `ChunkedStreamReader` as a replacement for [`ChunkedStreamIterator` from `package:chunked_stream`](https://github.com/google/dart-neats/blob/4f9e2ce596c71925a4de26cce96b3193d949da3e/chunked_stream/lib/src/chunked_stream_iterator.dart).
Motivation: We would like to use `ChunkedStreamIterator` in Dart SDK and avoid dependency on `package:chunked_stream`. Also for consuming a chunked byte stream in pull-fashion, this has proven very useful :)
I refactored the code a bit, mostly just cleanup, better documentation comments, and rename the class so that code that imports both `package:async` and `package:chunked_stream` won't get a conflict. Test cases are the same to ensure easy migration.
------
Credits @walnutdust for the original `ChunkedStreamIterator` in …

Add ChunkedStreamReader

---

lib/src/stream_queue.dart

- Use a noun phrase to document the `hasNext` getter. The `next` and
`peek` getters keep their verb phrase doc comments since the side
effects are critical distinctions between these methods. If we were
writing this today, `next()` would be a method.
- Change `_failClosed()` which returns an error, to `_checkClosed()`
which checks the condition and optionally closes. Avoid nesting the
majority of method behavior in a conditional.
- Use `RangeError.checkNotNegative` over a conditional.
- Change bare `Future` to `Future<void>` in code examples.
- Make `withTransaction` `async` since there is no longer a blocker now
that async methods start running synchronously.

Style tweaks in stream_queue.dart

---

CHANGELOG.md
lib/async.dart
lib/src/stream_sink_extensions.dart
lib/src/stream_sink_transformer/reject_errors.dart
test/reject_errors_test.dart

This makes it easy for authors to expose sinks that can't natively
consume errors, but still handle them in a consistent and robust
manner.

Add a StreamSink.rejectErrors() extension method

---

lib/src/future_group.dart

There is no `stream` member to reference.

Fix docs in FutureGroup

---

CHANGELOG.md
lib/src/stream_group.dart
pubspec.yaml
test/stream_group_test.dart

This would put the StreamGroup into an inconsistent state where it
would believe itself to be active, but only some streams would have
subscriptions. This was exacerbated by dart-lang/sdk#45815, which
meant that even though _onListen threw an error a StreamSubscription
was created and returned, so further callbacks could still be called.
Now instead of going into an inconsistent state, the StreamGroup
simply cancels itself.

Fix a StreamGroup bug when a component stream's listen() throws

---

CHANGELOG.md
lib/src/cancelable_operation.dart
test/cancelable_operation_test.dart

Fixes #172
The `isCompleted` boolean does not necessarily indicate that
`valueOrCancellation` will complete with a value. If the completer was
completed with a `Future` and then canceled before that argument
invokes the listener callback, the `valueOrCancellation` future will
complete with `null` but `isCompleted` will be true. We only have a
value to pass to `onValue` when the completer was completed and not
canceled.
Add tests for the behavior of `then` when `cancel` is called after
`completer.complete`, both when it was completed with a Future and a
non-Future value.
Move the initialization for `originalCompleter` to the `setup` for the
tests so that it can be used before calling `then`.

Don't invoke onValue for a canceled operation

---

CHANGELOG.md
lib/src/stream_extensions.dart
pubspec.yaml

Based on the doc comment on the unmerged Iterable.slices from
https://github.com/dart-lang/collection/pull/191
Drop extra newline in changelog, sort deps, and drop `-nullsafety` from
constraints.

Add doc comment on Stream.slices

---

CHANGELOG.md
lib/src/chunked_stream_reader.dart
pubspec.yaml
test/chunked_stream_reader.dart

* Add an internal `_offset` to track offset in `_buffer`, reducing the
number of times we need to create a sublist internally.
* Specialize to handle cases where `_buffer` is a `Uint8List` by
creating a `Uint8List.sublistView` when we need to split a chunk.
Fixes #181.

Faster ChunkedStreamReader.

---

CHANGELOG.md
lib/src/byte_collector.dart
pubspec.yaml

When this utility was first written `BytesBuilder` was only importable
from `dart:io`. Now that it may be imported from the cross platform
`dart:typed_data` it can be used in `package:async`.

Use BytesBuilder for collectBytes

---

lib/src/byte_collector.dart

The previous implementation of `collectBytes` would return a `Uint8List`
where the `lengthInBytes` and `buffer.lengthInBytes` matched. This
property isn't an intended guarantee, however since some callers may
rely on it for correct behavior it is safer to retain it. Use `copy: false`
so that the buffer used in `takeBytes` has the same length as the data.

Avoid copying with BytesBuilder

---

CHANGELOG.md
lib/src/stream_group.dart
test/stream_group_test.dart

Fix broadcast StreamGroup ignores streams added after StreamGroup is canceled

---

CHANGELOG.md
pubspec.yaml

I made the previous publish at a commit too early. Move the changelog
for the `StreamGroup` bug fix to a new version and prepare to publish.

Prepare to publish (again)

---

CHANGELOG.md
lib/src/sink_base.dart
pubspec.yaml
test/io_sink_impl.dart
test/sink_base_test.dart

The approach was not considered a good fit for the package API,
and we'll remove the classes and consider another approach, if one is needed.

Deprecate sink_base classes.

---

.github/workflows/test-package.yml
lib/src/cancelable_operation.dart
pubspec.yaml

The arguments that were passed match the intention of the
`ArgumentError` constructor, while the `ArgumentError.value` constructor
reverses the message and argument name, and includes the argument value.
Including the value is not useful in this case since it is always `[]`
and in most cases won't be the exact instance that was passed because of
the `.toList()` call which would usually construct a copy.
Bump the min SDK constraint to `2.14` which is the first release
allowing the `name` argument to the `ArgumentError` constructor.

Fix an ArgumentError constructor call

---

lib/src/stream_extensions.dart

I missed that we didn't wait for the `subscription.cancel` to complete before reporting the event, which is always good style for stream subscriptions.
With `cancelOnError:true`, the `onError` event won't happen before the auto-`cancel` has completed.

Let `firstOrNull` extension method wait for `cancel` to complete.

---

CHANGELOG.md
lib/src/stream_group.dart

This is probably technically breaking for some cases - but it doesn't look to be breaking for anything at all internally, so I think in practice it is not breaking. Finishing up a global presubmit now with all the changes (but already did one with a subset).
WDYT?

update some StreamGroup apis to Future<void> from Future<dynamic>

---

test/cancelable_operation_test.dart

A bug in `Completer.complete` could allow the completion to happen synchronously, even on a non-synchronous completer.
That is being fixed in the SDK.
That affects `AsyncMemoizer`, which uses a pattern which could trigger the bug.
The `CancelableOperation`  completer uses such a memoizer and that would cause a `cancel` to trigger `.then` listeners synchronusly.
With that no longer being the case, two tests needed to insert delays to wait for the cancellation to be propagated to the listner.

Update `CancelableOperation` test to not assume completion happens synchronously.

---

lib/src/cancelable_operation.dart

Make `CancelableOperation` not hold onto unnecessary callbacks.
The existing `CancelableOperation` contains two completers,
where at most one will ever complete. Listeners added to
the other completer's future will never be released as
long as the operation is alive, even after the operation
has otherwise completed.
This change drops reference to the other completer when
one completer is chosen for completion.
That can allow the completer, its future, and that future's listeners
to be GC'ed when it's known that they'll never be relevant again.
The change has one visible effect: If asking for the `value`
future after the operation has been cancelled and the value
completer has been released, you'll get a new future,
which also never completes, which is not identical to
other futures …

Avoid leaking unreachable listeners on `CancelableOperation`.

---

lib/src/cancelable_operation.dart
test/cancelable_operation_test.dart

A prior change made it so that a `.then` on a `CancelableOperation`
would call the `onValue`/`onError` callback even if the
returned operation was cancelled beteen the time of the `then`
and the time the original operation completed.
The result would not show up in the cancelled operation,
but the callbacks would run.
This change blocks calling the callbacks if the returned operation
has been cancelled.
Q.v. #204

Revert change of visible behavior in `CancelableOperation`.

---

CHANGELOG.md
lib/src/async_cache.dart
test/async_cache_test.dart

The `AsyncCache.ephemeral()` cache would invalidate
the `fetch` cache after a `Duration.zero` wait.
That allows a large number of microtasks to happen between
the `fetch` completing and the cache being invalidated.
Instead the cache is now invalidated immediately when the fetched
request completes.
Fixes #151

Make ephemeral async cache clear sooner.

---

CHANGELOG.md
lib/src/cancelable_operation.dart

Closes #212
Authors are more likely to expect propagation, and not cancelling is
often a hidden inefficiency so it often goes unnoticed and untested.
Update the doc comment to focus on the 3 ways an operation can end - as
a value, an error, or a cancellation. This will hopefully make it more
clear that the `onCancel` callback does not relate to the cancellation
of the returned operation.

Change the default propagateCancel argument

---

CHANGELOG.md
lib/src/cancelable_operation.dart
pubspec.yaml
test/cancelable_operation_test.dart

Towards #210
Once combined with `Completer.completeOperation` this signature adds
significant flexibility for chaining Cancelable work following other
async work.
Move the existing `.then` implementation to `.thenOperation` since the latter
is more general.

Add CancelableOperation.thenOperation

---

CHANGELOG.md
lib/src/cancelable_operation.dart
test/cancelable_operation_test.dart

Towards #210
Combined with `CancelableOperation.thenOperation` this allows chaining
cancelable work that can be canceled at multiple points.

Add CancelableCompleter.completeOperation

---

CHANGELOG.md
lib/src/cancelable_operation.dart

This is useful in tests which stub behavior for an API which returns `CancelableOperation`. It has more clear semantics and is shorter than `CancelableOperation.fromFuture(Future.value(...))`.
Take a `T` instead of a more general `FutureOr<T>` to satisfy both cases because it allows simplifying the API with no `onCancel` support.

Add CancelableOperation.fromValue

---

CHANGELOG.md
README.md
pubspec.yaml

It looks like https://github.com/dart-lang/async/commit/c59c7c51cc2a1b1fc49a2d853d413bd3a92126e9 landed after the last publish; this PR moves the changelog entry into a new section - `2.11.0-dev`. If we want to republish immediately w/ the new version, we can instead rev to `2.11.0` in this PR.

update changelog and pubspec version

---

CHANGELOG.md
lib/src/stream_extensions.dart
pubspec.yaml
test/stream_extensions_test.dart

The immediate motivation for this is to buffer stderr from a subprocess until we learn whether the subprocess completed successfully or not. It's important to consume the output eagerly so the process doesn't deadlock after saturating the OS and/or `dart:io` buffers, but we don't want to print it at all if the process completes successfully.
I think it's generally useful to have an explicit way of doing this, since otherwise users may naively try to write `Stream.pipe(StreamController)` which doesn't actually buffer output if the controller doesn't have a listener.

Add `StreamExtensions.buffer()`

---

test/stream_queue_test.dart

Towards #229
Add a skipped test demonstrating the sequence of interaction with a
StreamQueueTransaction that leads to a `StateError` during the call to
`transaction.reject()`.

Regression test for error rejecting transaction

---

CHANGELOG.md
lib/src/cancelable_operation.dart
pubspec.yaml
test/cancelable_operation_test.dart

Add a test which chains through multiple `.then` calls and then cancels
the original operation. This test passes with the original code, but
starts failing after fixing a bug in `Completer.complete` in the SDK.
https://dart-review.googlesource.com/c/sdk/+/258929
- Add a list of extra completers to forward cancellation. In places
where the cancellation had been forwarded through a `whenComplete`,
add to the list of extra cancellations instead. This allows the Future
return by the outer cancellation to wait for the other callbacks to
complete before firing.
- When setting up forwarding on an already canceled completer,
immediately forward the cancellation.
- When forwarding cancellations, don't repeatedly call `_cancel()` on a
completer which has already been canceled.
- In `race()`, …

Synchronously forward chained cancellations
